version: 2
jobs:
  build:
    docker:
      - image: raviqqe/ein-ci
    working_directory: /go/src/github.com/ein-lang/ein
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            go get -d -t ./...
            go get -u github.com/alecthomas/gometalinter
            $GOPATH/bin/gometalinter --install
      - run:
          name: Lint
          command: $GOPATH/bin/gometalinter --deadline 5m ./...
      - run:
          name: Build runtime
          command: |
            cd runtime
            cargo build --release
      - run:
          name: Build command
          command: go build
      - run:
          name: Unit test
          command: |
            go test -covermode atomic -coverprofile coverage.txt -race ./...
            curl -s https://codecov.io/bash | bash
      - run:
          name: Integration test
          command: |
            bundler install
            bundler exec cucumber EIN_RUNTIME_PATH=$PWD PATH=$PWD:$PATH
